name: VRT

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: vrt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: npm ci

      - run: npm run build-storybook

      - uses: sgash708/chromagic@perf/storycap-parallel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          viewport: "390x844,1280x800"
